# Form implementation generated from reading ui file 'Ui_coding.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_CodingInterface(object):
    def setupUi(self, CodingInterface):
        CodingInterface.setObjectName("CodingInterface")
        CodingInterface.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(CodingInterface)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(parent=CodingInterface)
        self.widget.setMinimumSize(QtCore.QSize(0, 50))
        self.widget.setObjectName("widget")
        self.verticalLayout.addWidget(self.widget)
        self.codeeditor = CodeEditor(parent=CodingInterface)
        self.codeeditor.setMinimumSize(QtCore.QSize(0, 50))
        self.codeeditor.setObjectName("codeeditor")
        self.verticalLayout.addWidget(self.codeeditor)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.comboBox = ComboBox(parent=CodingInterface)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.horizontalLayout.addWidget(self.comboBox)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton = PushButton(parent=CodingInterface)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.plainTextEdit = PlainTextEdit(parent=CodingInterface)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.verticalLayout.addWidget(self.plainTextEdit)

        self.retranslateUi(CodingInterface)
        QtCore.QMetaObject.connectSlotsByName(CodingInterface)

    def retranslateUi(self, CodingInterface):
        _translate = QtCore.QCoreApplication.translate
        CodingInterface.setWindowTitle(_translate("CodingInterface", "Form"))
        self.comboBox.setItemText(0, _translate("CodingInterface", "python"))
        self.pushButton.setText(_translate("CodingInterface", "运行"))
from ..components.code_editor import CodeEditor
from qfluentwidgets import ComboBox, PlainTextEdit, PushButton
